from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import pandas as pd

# Load data
health_scores = pd.read_csv(
    "data/processed/health_scores_v2.csv"
)

# Example company
company = "TCS"

company_data = health_scores[
    health_scores["company_id"] == company
]

latest = company_data.iloc[-1]

pdf_file = f"{company}_report.pdf"

c = canvas.Canvas(
    pdf_file,
    pagesize=letter
)

c.setFont("Helvetica-Bold", 18)
c.drawString(
    50,
    750,
    f"{company} Financial Report"
)

c.setFont("Helvetica", 12)

c.drawString(
    50,
    700,
    f"Health Score: {latest['health_score_v2']:.2f}"
)

c.drawString(
    50,
    675,
    f"Health Band: {latest['health_band']}"
)

c.drawString(
    50,
    650,
    f"ROE: {latest['return_on_equity_pct']:.2f}"
)

c.drawString(
    50,
    625,
    f"Net Profit Margin: {latest['net_profit_margin_pct']:.2f}"
)

c.drawString(
    50,
    600,
    f"Operating Profit Margin: {latest['operating_profit_margin_pct']:.2f}"
)

c.drawString(
    50,
    550,
    "Generated by N100 Financial Intelligence Platform"
)

c.save()

print(
    f"PDF saved successfully: {pdf_file}"
)